{ pkgs, ... } : with pkgs; [
    alacritty
    bat
    curl
    ldns
    libsForQt5.qt5.qtgraphicaleffects
    libsForQt5.qt5.qtquickcontrols
    lynx
    man-pages
    man-pages-posix
    most
    neovim
    onefetch
    python3
    trash-cli
    tree
    xorg.xrandr
    zsh
    zsh-autosuggestions
    zsh-syntax-highlighting
]
